# Generated by Django 4.1.1 on 2023-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
