# Generated by Django 4.1.1 on 2023-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_image', models.FileField(upload_to='tips/')),
                ('tip_title', models.CharField(max_length=1000)),
                ('datetime_posted', models.DateTimeField(auto_now_add=True)),
                ('tips_type', models.CharField(choices=[('content', 'Content'), ('video', 'Video'), ('audio', 'Audio')], default='content', max_length=10)),
                ('audio_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('writing_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
