# Generated by Django 4.1.1 on 2024-06-25 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('azampay_transaction_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('provider', models.CharField(max_length=1000)),
                ('is_success', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_number', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
