# Generated by Django 4.1.1 on 2024-06-25 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-datetime_posted']},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='deadline_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_post_url',
            field=models.TextField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            #field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            #field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='user_cvs/')),
                ('preferred_categories', models.ManyToManyField(blank=True, null=True, to='jobpost.jobcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobpost.userprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobpost.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='jobpost.jobcategory'),
        ),
        migrations.CreateModel(
            name='SavedJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job_post')},
            },
        ),
    ]
