# Generated by Django 4.1.1 on 2025-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_jobcategory_alter_jobpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='categories',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
