# Generated by Django 4.1.1 on 2025-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0004_alter_jobpost_salary_max_alter_jobpost_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
    ]
