# Generated by Django 4.1.1 on 2025-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0005_alter_jobpost_salary_max_alter_jobpost_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_post_url',
            field=models.CharField(max_length=1000),
        ),
    ]
