# Generated by Django 4.1.1 on 2025-03-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0006_alter_jobpost_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobcategory')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
            ],
        ),
    ]
