# Generated by Django 4.2.20 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0007_jobpostcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(upload_to='company_images/'),
        ),
    ]
