# Generated by Django 4.2.20 on 2025-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0008_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(),
        ),
    ]
